### ISSUE TITLE
Discussão sobre as tecnologias do front-end

### ISSUE THREAD

**Issue by nandomoreirame** [php-pr/portal-php-pr#3]
Galera, vamos em paralelo com o Wireframe e Layout fazer o levantamento do que iremos utilizar para desenvolvimento front-end.
1. SASS, Less ou Stylus
2. Gulp ou Grunt
3. [Bootstrap](http://getbootstrap.com/) (sass ou less), [Foundation](http://foundation.zurb.com/) (ou qualquer outro framework css) ou fazer o CSS do zero
4. Sistema de grids? (mesmo usando algum framework vale lembrar que com o [Jeet](http://jeet.gs/) é bem melhor)
5. Cross browser? IE9 pra cima ou daremos suporte ao IE7 e 8? (não custa perguntar né xD)

Se tiver alguma tecnologia que vale a pena usarmos diz ai, vamos escolher a que melhor se adapta ao projeto e as pessoas envolvidas.

E vamos as votações e questionamentos.

**Comment by joridos** [comment]
Minhas sugestões são:

* Sass (tem umas coisas a mais que Less e Stylus é mais usado em projetos MEAN).
* Grunt (para min tanto faz na verdade só que a galera ta mais acostumada com grunt, mas se forem de gulp para min ta blz tbm).
* Bootstrap (para min tanto faz novamente, mas a galera já esta acostumada a usar então...).
* Acho uma boa usar o Jeet.
* Penso em primeiro fazermos ele todo e depois deixarmos Cross browser.

**Comment by kleberksms** [comment]
concordo com @joridos, mas meu forte não é front, acho que nesta vou mais aprender com vocês que dar dica
